  mysql:
    container_name: mysqlTest
    environment:
      MYSQL_ROOT_PASSWORD: ${mysqlRootPassword}
    ports:
    - '${mysqlLocalPort}:3306'
    volumes:
    - '${localContainerData}/mysqlTest:/var/lib/mysql'
    image: 'mysql:latest'
    command: --default-authentication-plugin=mysql_native_password
    restart: always