  ntp:
    image: cturra/ntp:latest
    container_name: ${ntpContainerName}
    restart: always
    ports:
      - 123:123/udp
    cap_add:
      - SYS_NICE
      - SYS_RESOURCE
      - SYS_TIME
    environment:
      - NTP_SERVERS=${ntpServers}